version: '3'

services:
  # web:
  #   build: .
  #   command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgresdb

  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: drf_db
      POSTGRES_USER: drf_user
    ports:
      - "5432:5432"